### ISSUE TITLE
Login with external Auth provider

### ISSUE THREAD

**Issue by sdil** [lupas/nuxt-firebase-demo#29]
Firebase Auth supports many auth providers (eg. Google, Facebook, Github, Twitter, Oauth, etc.). Example of using Google auth for firebase login is available [here](https://firebase.google.com/docs/reference/js/firebase.auth.GoogleAuthProvider).

It would be great if we have an example of how to use Google Auth with this nuxt/fire module.

Thanks.

**Comment by rodrigopv** [comment]
Hi,

While searching how to implement Firebase into nuxtjs in the best possible way I found @nuxtjs/firebase. There is still not much documentation about it, almost all guides out there just use firebase.js directly.

I've made a guide about how to use social auth along with @nuxtjs/firebase: https://dev.to/rodrigopv/nuxtjs-firebase-social-auth-3afe

Maybe we can all contribute to making more documentation about this amazing library!

**Comment by sdil** [comment]
@rodrigopv That is a very good tutorial!

Maybe you can open a Pull Request here by adding that social login button?

**Comment by lupas** [comment]
Hey @sdil  and @rodrigopv 

First, thanks @rodrigopv for this great tutorial, I like it! I added the tutorial to the ["Links" section of our documentation](https://firebase.nuxtjs.org/community/links) for reference, hope that's okay :)

@sdil
I added "writing a tutorial/example on how to use Google Auth with this nuxt/fire module" to the sticky issue  https://github.com/nuxt-community/firebase-module/issues/380 and will work on it when I find time, thanks for the input :)

If there's any other issues or questions regarding the module please open up an issue directly on the [module repository](https://github.com/nuxt-community/firebase-module) :)

**Comment by sdil** [comment]
Thank you @lupas :D
