### ISSUE TITLE
Emulator requirement not clear

### ISSUE THREAD

**Issue by chrsr** [lupas/nuxt-firebase-demo#32]
Hi, great demo app - thanks heaps.

What I found when trying to get up and running is that it wasn't clear I needed the Firebase tooling and emulators running to run the demo locally. Thought it would be clearer if this step was added to the readme.

**Comment by lupas** [comment]
Thanks @chrsr - appreciate it!

Please excuse the late response. I just merged your PR.

FYI: You can also decide to disable the emulators in this project and then play around against the Firebase backend.
