### ISSUE TITLE
can we have any example using OAuth

### ISSUE THREAD

**Issue by vvsubash** [lupas/nuxt-firebase-demo#34]
Hey, Really great example but I'm not able to wrap my head around google OAuth can we have an example using auth providers.

Thank You.

**Comment by lupas** [comment]
Hey @vvsubash 

Using auth providers works exactly the same way in the regular Javascript SDK as when using it with Nuxt - there is no much difference.

Just make sure to use `this.$fire.auth` to create the auth provider, and then you can use that provider as described in the [Firebase Docs](https://firebase.google.com/docs/auth/web/google-signin)

```js
var provider = new this.$fire.auth.GoogleAuthProvider();
```

**Comment by vvsubash** [comment]
Thank you.
