### ISSUE TITLE
Error with $fire

### ISSUE THREAD

**Issue by damianlluch** [lupas/nuxt-firebase-demo#39]
Hello, people. I am trying to integrate this module to my project. Specifically to use push notifications.

I'm getting this error, and I haven't found anything about it.

![image](https://user-images.githubusercontent.com/1463804/107129081-37434900-68c3-11eb-9c4c-ed6fb7998e2b.png)

Any suggestions?

Thanks!

**Comment by lupas** [comment]
@damianlluch 
Can you try doing this in your tsconfig.json file?

https://firebase.nuxtjs.org/tutorials/typescript

**Comment by damianlluch** [comment]
thanks bro!!
