### ISSUE TITLE
Push Notifications: Actions not showing

### ISSUE THREAD

**Issue by damianlluch** [lupas/nuxt-firebase-demo#41]
Hello, me again

I get the push notifications, but on the desktop I don't have the actions when the push notification appears.
In my nuxt.config I have copied your code, but it doesn't work.

Any suggestions?

```js
messaging: {
        createServiceWorker: true,
        actions: [
          {
            action: 'goToLupasGithub',
            url: 'https://github.com/lupas',
          },
          {
            action: 'goToModuleGithub',
            url: 'https://github.com/nuxt-community/firebase-module',
          },
        ],
        fcmPublicVapidKey:
          'mypublickey',
      },
    },
```

**Comment by lupas** [comment]
@damianlluch 

Hard to say what's wrong, it works for me. What does "on the desktop" mean? Which browser are you using and which version?

<img width="358" alt="Screenshot 2021-02-16 at 22 19 40" src="https://user-images.githubusercontent.com/4020037/108122762-1342ed00-70a5-11eb-93ea-a4d1477f4b1b.png">

**Comment by lupas** [comment]
Closing due to no answer.
