### ISSUE TITLE
Send push notifications from functions

### ISSUE THREAD

**Issue by damianlluch** [lupas/nuxt-firebase-demo#42]
Hello, me again

I'm testing the button that calls the function that sends the push notification, and I get this error.

Any suggestions?

Thanks!

![image](https://user-images.githubusercontent.com/1463804/108078031-79138280-706d-11eb-9130-96d19b57ef5a.png)

**Comment by lupas** [comment]
Do you have Firebase functions setup in your Nuxt/Firebase config? How are you accessing httpsCallable in your code?

Please share a code example, otherwise we cannot debug your problem.

**Comment by lupas** [comment]
Yep, getting the same error with the Demo. Interesting. Will have a look at it.

**Comment by lupas** [comment]
@damianlluch 
I just updated all dependencies and don't experience the error anymore. Could you try that (or use the newest version of the demo repo)?

Let me know if you still run into this issue.
