### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by roselily8** [lupas/nuxt-firebase-demo#44]
Hi Lupas,

I am getting a 403 when loading the demo. I've changed the firebase credentials in config.

Uncaught (in promise) t {code: "auth/internal-error", message: "{"error":{"code":403,"message":"Requests to this A…7218","service":"securetoken.googleapis.com"}}]}}", a: null}

**Comment by roselily8** [comment]
I resolved the issue. But now I have a question. How long is the auth token valid for?

**Comment by lupas** [comment]
Hey @roselily8 

Sorry for the late response.
The demo should work again - and a custom token is valid for an hour, see https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk
