### ISSUE TITLE
How to implement messaging?

### ISSUE THREAD

**Issue by zarpio** [lupas/nuxt-firebase-demo#46]
Can you please provide a demo or well/detailed written example? 

Found a [link](https://stackoverflow.com/questions/58163755/how-to-implement-firebase-cloud-messaging-fcm-with-nuxt-js), but it is not helping me nor your documentation.

Please provide a full example, thanks.

**Comment by lupas** [comment]
Hi @zarpio 
Messaging is a function that has nothing to do with Nuxt or this module per se, please refer to StackOverflow with general questions about how to use Firebase.

I nevertheless added your request here, maybe someone wants to create a documentation the future:
https://github.com/nuxt-community/firebase-module/issues/380
