### ISSUE TITLE
How to update password for selfuser and admin set update password user ?

### ISSUE THREAD

**Issue by hengseyha** [lupas/nuxt-firebase-demo#50]
could you please provide the example for update user password with firebase nuxt?
var user = this.$fire.auth.currentUser;
              console.log(user)
              try{
                  let data = await user.updatePassword(this.newPassword)
                  console.log(data)
              }catch(e){
                  console.log(e)
              }

**Comment by lupas** [comment]
This should do it:

```js
// Ask user to sign in
await this.$fire.auth.signInWithEmailAndPassword(
  this.user.email,
  this.user.oldpass
)
// Update password
await this.$fire.auth.currentUser.updatePassword(this.newPass)
```
